---
# tasks file for role_jenkins
- name: installation de java
  yum:
    name: java-1.8.0-openjdk-devel
    state: present
- name: téléchargement jenkins
  get_url:
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
    dest: /usr/lib/jenkins/jenkins.war
    mode: '770'
- name: configuration du service jenkins
    template:
      src: jenkins.service.j2
      dest: /etc/systemd/system/jenkins.service
- name: rechargement des démons
  systemd:
    daemon_reload: yes
- name: démarrage de jenkins, actuel et au reboot
    service:
      name: jenkins
      state: started
      enabled: yes
      

      


